#Eureka\u76F8\u5173\u914D\u7F6E
server:
  port: 9203
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/


#Stream\u76F8\u5173\u914D\u7F6E
spring:
  application:
    name: youqu-service-msg
  cloud:
    stream:
      bindings: # \u670D\u52A1\u7684\u6574\u5408\u5904\u7406
        input: # \u8FD9\u4E2A\u540D\u5B57\u662F\u4E00\u4E2A\u901A\u9053\u7684\u540D\u79F0\uFF0C\u5728\u5206\u6790\u5177\u4F53\u6E90\u4EE3\u7801\u7684\u65F6\u5019\u4F1A\u8FDB\u884C\u8BF4\u660E
          destination: myOutput # \u8868\u793A\u8981\u4F7F\u7528\u7684Exchange\u540D\u79F0\u5B9A\u4E49
          content-type: application/json # \u8BBE\u7F6E\u6D88\u606F\u7C7B\u578B\uFF0C\u672C\u6B21\u4E3A\u5BF9\u8C61json\uFF0C\u5982\u679C\u662F\u6587\u672C\u5219\u8BBE\u7F6E\u201Ctext/plain\u201D
          group: myInput  #queue\u540D

  rabbitmq:
    addresses: 47.107.126.98:5672
    username: guest
    password: guest

  # QQ邮箱设置
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 664650322@qq.com #发送邮件的邮箱地址
    password:  ivhkrc*****kbdcf #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 1016767658@qq.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    default-encoding: utf-8

# 邮件过期时间
time:
  minute: 5