server:
  port: 9999
spring:
  application:
    name: youqu-service-zuul
  servlet:
    multipart:
      max-request-size: -1   #解除文件上传大小限制
      max-file-size: -1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
# 路由分发
zuul:
  routes:
    youqu-invitation: #自定义路由名称
      path: /invitation/** #路由规则
      serviceId: youqu-service-provider-invitation #微服务ID
    youqu-qiniu:
      path: /other/**
      serviceId: youqu-service-other
    youqu-chat:
      path: /chat/**
      serviceId: youqu-service-provider-chat
    youqu-user:
      path: /user/**
      serviceId: youqu-service-provider-user
  host:
    connect-timeout-millis: 12000 # 超时时间12秒
    socket-timeout-millis: 11000
ribbon:
  ReadTimeout: 10000  # 超时时间10秒
  SocketTimeout: 10000