server:
  port: 9502
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/


#Spring Cloud Stream相关配置
spring:
  application:
    name: youqu-service-provider-user
  cloud:
    stream:
      bindings: # 服务的整合处理
        output: # 这个名字是一个通道的名称，在分析具体源代码的时候会进行说明
          destination: myOutput # 表示要使用的Exchange名称定义
          content-type: application/json # 设置消息类型，本次为对象json，如果是文本则设置“text/plain”
          #binder: defaultRabbit # 设置要绑定的消息服务的具体设置
  rabbitmq:
     addresses: 47.107.126.98:5672
     username: guest
     password: guest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.107.126.98:3306/youqu?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: 123456


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名法

#日志打印
logging:
  level:
    cn.zdxh.user.mapper : debug

