server:
  port: 9502
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/


#Spring Cloud Stream相关配置
spring:
  application:
    name: youqu-service-provider-user
  cloud:
    stream:
      bindings: # exchange与queue绑定
        email_output: # 邮件生产者设置output
          destination: email.exchange # exchange
          content-type: application/json # 消息传输类型
          group: email.queue  # queue
          binder: youqu_rabbit
        log_output: # 日志生产者设置output
          destination: log.exchange
          content-type: application/json
          group: log.queue
          binder: youqu_rabbit #自定义名称
      binders:
        youqu_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 134.175.168.124 #134.175.168.124:5672
                port: 5672
                username: guest
                password: 25802580
#  rabbitmq:
#     addresses: 134.175.168.124:5672    #134.175.168.124:5672
#     username: guest
#     password: 25802580
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.175.168.124:3306/youqu?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: Aa123456.*



mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名法

#日志打印
logging:
  level:
    cn.zdxh.user.mapper : debug
    cn.zdxh.user.client.RedisClient : debug

