eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/

server:
  port: 9204
spring:
  application:
    name: youqu-service-other
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://134.175.168.124:3306/youqu?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
    username: root
    password: Aa123456.*
  servlet:
    multipart:
      max-request-size: -1
      max-file-size: -1
  cloud:  # Spring Cloud Stream 相关配置
    stream:
      bindings: # exchange与queue绑定
        email_input: # 邮件消费者设置input
          destination: email.exchange # exchange
          content-type: application/json # 消息传输类型
          group: email.queue  # queue
          binder: youqu_rabbit
        log_input: # 日志消费者设置input
          destination: log.exchange
          content-type: application/json
          group: log.queue
          binder: youqu_rabbit
      binders:
        youqu_rabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: 134.175.168.124
                port: 5672
                username: guest
                password: 25802580

  redis:
    host: 134.175.168.124   #redis相关配置 134.175.168.124
    port: 6379
    lettuce:
      pool:
        max-active: 3
        max-idle: 3
        max-wait: 6000ms # -1ms不超时
        min-idle: 0
    password: 25802580

#  rabbitmq: # RabbitMQ相关配置
#    addresses: 134.175.168.124:5672    #134.175.168.124:5672
#    username: guest
#    password: 25802580

  # QQ邮箱设置
  mail:
    host: smtp.qq.com #发送邮件服务器
    username: 664650322@qq.com #发送邮件的邮箱地址
    password: knxorvvbedwybeah #客户端授权码，不是邮箱密码，这个在qq邮箱设置里面自动生成的
    properties.mail.smtp.port: 465 #端口号465或587
    from: 664650322@qq.com # 发送邮件的地址，和上面username一致
    properties.mail.smtp.starttls.enable: true
    properties.mail.smtp.starttls.required: true
    properties.mail.smtp.ssl.enable: true
    properties.mail.smtp.auth: true
    default-encoding: utf-8

# 邮件验证码过期时间
time:
  minute: 10


# 七牛云相关配置
qiniu:
  access: h1YFKAojPVBccsZ93Lc7tIGgxy73rEiKc-MEoQy_
  secret: 98b5GM0KWayWN5xiBmdo5GBHhUeMHYallDU5jQJW
  bucket: youqu-xh
  url: http://qiniu.ningxiaojian.top/


# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名法

#日志打印
logging:
  level:
    cn.zdxh.other.log.mapper : debug